import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import YAML from "yaml";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "../../..");
const configDir = path.join(repoRoot, "config");
const outputPath = path.join(repoRoot, "apps/web/src/data/config.ts");

const readYaml = async (fileName) => {
  const content = await readFile(path.join(configDir, fileName), "utf8");
  return YAML.parse(content);
};

const moduleMapping = await readYaml("module_mapping.yaml");
const tagSynonyms = await readYaml("tag_synonyms.yaml");
const pipelineConfig = await readYaml("pipeline.yaml");

if (!moduleMapping?.module_systems || !moduleMapping?.mappings) {
  throw new Error("module_mapping.yaml 缺少 module_systems 或 mappings 配置。");
}

if (!tagSynonyms?.tags) {
  throw new Error("tag_synonyms.yaml 缺少 tags 配置。");
}

const output = `// This file is generated by scripts/generate-config.mjs. Do not edit directly.

export const moduleSystems = ${JSON.stringify(
  moduleMapping.module_systems,
  null,
  2
)} as const;

export const moduleMappings = ${JSON.stringify(
  moduleMapping.mappings,
  null,
  2
)} as const;

export const tagSynonyms = ${JSON.stringify(tagSynonyms.tags, null, 2)} as const;

export const pipelineConfig = ${JSON.stringify(pipelineConfig, null, 2)} as const;

export type ModuleSystem = (typeof moduleSystems)[number];
export type ModuleMapping = (typeof moduleMappings)[number];
export type TagSynonyms = typeof tagSynonyms;
export type PipelineConfig = typeof pipelineConfig;
`;

await writeFile(outputPath, output, "utf8");
console.log(`Config generated: ${path.relative(repoRoot, outputPath)}`);
