// This file is generated by scripts/generate-data.mjs. Do not edit directly.

export type BuildLogStep = {
  name: string;
  status: "success" | "failed";
  error_samples?: string[];
  truncated?: boolean;
  quota_exhausted?: boolean;
};

export type BuildLog = {
  id: string;
  started_at: string;
  finished_at: string | null;
  status: "running" | "success" | "partial" | "failed";
  incomplete_data: boolean;
  truncated: boolean;
  quota_exhausted: boolean;
  steps: BuildLogStep[];
  error_samples: string[];
};

export const buildLogs: BuildLog[] = [];
