// This file is generated by scripts/generate-config.mjs. Do not edit directly.

export const moduleSystems = [
  {
    "id": "lumen",
    "name_zh": "Lumen 全局光照",
    "name_en": "Lumen Global Illumination",
    "description_zh": "动态全局光照与反射相关的更新。",
    "description_en": "Updates related to dynamic global illumination and reflections.",
    "item_count": null
  },
  {
    "id": "nanite",
    "name_zh": "Nanite 虚拟几何",
    "name_en": "Nanite Virtualized Geometry",
    "description_zh": "虚拟化几何体渲染与资产管线的更新。",
    "description_en": "Updates for virtualized geometry rendering and asset workflows.",
    "item_count": null
  },
  {
    "id": "rendering",
    "name_zh": "渲染总览",
    "name_en": "Rendering Overview",
    "description_zh": "渲染管线与通用渲染功能的更新。",
    "description_en": "Updates for the rendering pipeline and general features.",
    "item_count": null
  },
  {
    "id": "rhi",
    "name_zh": "RHI 与平台",
    "name_en": "RHI & Platforms",
    "description_zh": "渲染硬件接口与平台抽象层更新。",
    "description_en": "Updates for the Render Hardware Interface and platform layers.",
    "item_count": null
  },
  {
    "id": "materials",
    "name_zh": "材质与着色",
    "name_en": "Materials & Shading",
    "description_zh": "材质系统、着色模型与节点编辑更新。",
    "description_en": "Updates for materials, shading models, and node editing.",
    "item_count": null
  },
  {
    "id": "vsm",
    "name_zh": "虚拟阴影贴图",
    "name_en": "Virtual Shadow Maps",
    "description_zh": "虚拟阴影贴图相关的渲染更新。",
    "description_en": "Updates related to virtual shadow maps.",
    "item_count": null
  }
] as const;

export const moduleMappings = [
  {
    "module_code": "Renderer/Lumen",
    "module_system": "lumen"
  },
  {
    "module_code": "Lumen",
    "module_system": "lumen"
  },
  {
    "module_code": "Renderer/Nanite",
    "module_system": "nanite"
  },
  {
    "module_code": "Nanite",
    "module_system": "nanite"
  },
  {
    "module_code": "Renderer/VirtualShadowMaps",
    "module_system": "vsm"
  },
  {
    "module_code": "VirtualShadowMap",
    "module_system": "vsm"
  },
  {
    "module_code": "Renderer",
    "module_system": "rendering"
  },
  {
    "module_code": "Rendering",
    "module_system": "rendering"
  },
  {
    "module_code": "RHI",
    "module_system": "rhi"
  },
  {
    "module_code": "Platforms",
    "module_system": "rhi"
  },
  {
    "module_code": "Renderer/Materials",
    "module_system": "materials"
  },
  {
    "module_code": "Materials",
    "module_system": "materials"
  }
] as const;

export const tagSynonyms = {
  "GI": {
    "synonyms": [
      "global illumination",
      "gi",
      "全局光照"
    ]
  },
  "RT": {
    "synonyms": [
      "ray tracing",
      "rtx",
      "光线追踪"
    ]
  },
  "VSM": {
    "synonyms": [
      "virtual shadow maps",
      "virtual shadow map",
      "虚拟阴影贴图"
    ]
  },
  "VSMC": {
    "synonyms": [
      "virtual shadow map cache",
      "vsm cache",
      "阴影缓存"
    ]
  },
  "LOD": {
    "synonyms": [
      "level of detail",
      "细节层级"
    ]
  },
  "TSR": {
    "synonyms": [
      "temporal super resolution",
      "时序超分辨率"
    ]
  },
  "HZB": {
    "synonyms": [
      "hierarchical z-buffer",
      "层级 z 缓冲"
    ]
  },
  "SSS": {
    "synonyms": [
      "subsurface scattering",
      "次表面散射"
    ]
  }
} as const;

export const pipelineConfig = {
  "limits": {
    "daily_commits": 200,
    "backtrack_commits": 50,
    "max_sources": 3,
    "max_excerpt_words": 300,
    "max_files_listed": 30
  },
  "dedupe": {
    "tfidf_similarity": 0.92,
    "max_paragraphs": 3
  },
  "search": {
    "keywords_per_day": 150,
    "pages_per_keyword": 2,
    "results_per_page": 10
  },
  "thumbnails": {
    "max_size_px": 512,
    "max_kb": 200,
    "formats": [
      "jpeg"
    ]
  },
  "confidence": {
    "low_threshold": 0.5
  },
  "version": {
    "hotfix_tag_required": true
  }
} as const;

export type ModuleSystem = (typeof moduleSystems)[number];
export type ModuleMapping = (typeof moduleMappings)[number];
export type TagSynonyms = typeof tagSynonyms;
export type PipelineConfig = typeof pipelineConfig;
