// This file is generated by scripts/generate-data.mjs. Do not edit directly.

export type DailyReportItem = {
  id: string;
  title: string;
  version: string;
  published_at?: string | null;
  p1_score?: number;
};

export type DailyReportModule = {
  id: string;
  items: DailyReportItem[];
};

export type DailyReport = {
  date: string | null;
  modules: DailyReportModule[];
};

export const dailyReport: DailyReport = {
  "date": null,
  "modules": []
};
