// This file is generated by scripts/generate-data.mjs. Do not edit directly.

export const indexItems = [
  {
    "id": "lumen-radiance-cache",
    "title": "Lumen Radiance Cache update",
    "title_zh": "Lumen Radiance Cache update",
    "title_en": "Lumen Radiance Cache update",
    "version": "5.4",
    "published_at": "2024-05-10",
    "module_system": [
      "lumen"
    ],
    "change_type": "perf",
    "tags": [
      "Lumen",
      "GI"
    ],
    "summary_zh": "【AI 翻译】改进了 Lumen 辐射缓存更新调度，减少了大型场景中的卡顿。",
    "summary_en": "Improved the Lumen radiance cache update scheduling to reduce stalls in large scenes.",
    "credibility": "high",
    "p1_score": 8,
    "p1_reasons": [
      "change_type:perf+4",
      "high_sources:1+2",
      "sources:2+2"
    ]
  },
  {
    "id": "nanite-streaming",
    "title": "Nanite streaming budget improvements",
    "title_zh": "Nanite streaming budget improvements",
    "title_en": "Nanite streaming budget improvements",
    "version": "5.4",
    "published_at": "2024-04-28",
    "module_system": [
      "nanite"
    ],
    "change_type": "feature",
    "tags": [
      "Nanite",
      "LOD"
    ],
    "summary_zh": "【AI 翻译】为 Nanite 添加了流式预算诊断，帮助平衡内存驻留。",
    "summary_en": "Added streaming budget diagnostics for Nanite to help balance memory residency.",
    "credibility": "high",
    "p1_score": 9,
    "p1_reasons": [
      "change_type:feature+5",
      "high_sources:1+2",
      "sources:2+2"
    ]
  },
  {
    "id": "rendering-tsr",
    "title": "TSR pass refinement",
    "title_zh": "TSR pass refinement",
    "title_en": "TSR pass refinement",
    "version": "5.3",
    "published_at": "2023-09-20",
    "module_system": [
      "rendering"
    ],
    "change_type": "fix",
    "tags": [
      "TSR",
      "Rendering"
    ],
    "summary_zh": "【AI 翻译】通过改进历史裁剪修复了快速镜头移动中的 TSR 重影。",
    "summary_en": "Fixed TSR ghosting artifacts in fast camera pans by improving history clamping.",
    "credibility": "high",
    "p1_score": 6,
    "p1_reasons": [
      "change_type:fix+3",
      "high_sources:1+2",
      "sources:1+1"
    ]
  }
] as const;

export type IndexItem = (typeof indexItems)[number];
