// This file is generated by scripts/generate-data.mjs. Do not edit directly.

export const versions = [
  {
    "version": "5.4",
    "published_at": "2024-04-23",
    "release_notes_url": "https://dev.epicgames.com/documentation/en-us/unreal-engine/unreal-engine-5-4-release-notes"
  },
  {
    "version": "5.3",
    "published_at": "2023-09-06",
    "release_notes_url": "https://dev.epicgames.com/documentation/en-us/unreal-engine/unreal-engine-5-3-release-notes"
  },
  {
    "version": "5.2",
    "published_at": "2023-05-11",
    "release_notes_url": "https://dev.epicgames.com/documentation/en-us/unreal-engine/unreal-engine-5-2-release-notes"
  }
] as const;

export const latestMajor = "5.4" as const;

export type VersionMeta = (typeof versions)[number];
